config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :photos
  root "photos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file_location, PhotoImageUploader
  validates_presence_of :title, :date, :description, :file_location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, :only => [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.all.order(date: :desc)
  end 

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
       redirect_to photos_url
    else
      render :action => :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @photo.update_attributes(photo_params)
       redirect_to photo_path(@photo)
    else
      render :action => :edit
    end
  end

  def destroy
    @photo.destroy
    redirect_to photos_url
  end
  

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :date, :description, :file_location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photobook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>  
    </div>
    
  </body>
</html>

app/views/photos/_form.html.erb
 <header id="header">
  <div class="container">
    <nav>
      <div class="album_name">
        <h2>
          Photo Book
        </h2>
        <div class="ed_ne_button">
          <%= link_to "Back to index", photos_path %>
        </div>
      </div>
    </nav>
  </div>
</header>
<br>
<hr>
<br>

<% if @photo.errors.present? %>
  <ul>
    <% @photo.errors.each do |error, message| %>
    <li><%= "#{error.capitalize} #{message}" %></li>
    <% end %>
  </ul>
<% end %>


<div class="form container">
  <%= form_for @photo do |f| %>

    <div class="form-group"> 
      <%= f.label :title, "Titile" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">    
      <%= f.label :date, "Date" %>
      <%= f.text_field :date, class: "form-control" %>
    </div>

    <div class="form-group">    
      <%= f.label :file_location, "File Location" %>
      <%= f.file_field :file_location %>
    </div>



    <div class="form-group">    
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
      <%= f.submit %>
  <% end %>
</div>

  

app/views/photos/edit.html.erb
<%= render :partial => "form" %>

<br>
<div class="container">
  <div class="btn_page_article">
    <div class="p_page">
      <%= link_to "< back to show", photo_path %>
    </div>
  </div>
</div>

app/views/photos/index.html.erb
<header id="header">
  <div class="container">
    <nav>
      <div class="album_name">
        <h2>
          Photo Book
        </h2>
        <div class="createbutton">
          <%=link_to 'New Memory', new_photo_path %>
        </div>
      </div>
    </nav>
  </div>
</header>
<br>


<div class="container">
  <% @photos.each do |photo| %>
  <br><br>
  <div class="index_pic">
    <%= image_tag photo.file_location.url, style: 'max-height: 150px; max-width: 150px', class: "imgage-thumbnail" %>
  </div>
  <div class="summary">
    <div class="r-title">
      <h3><%= link_to photo.title, photo %></h3>
      <div class="r-date">
        <%= photo.date %>
      </div>
    </div>
    <div class="event_detail">
      <%= photo.description %>
    </div>
    <div class="controlbutton">
      <div class="b_edit">
        <%= link_to 'Edit' %>
      </div>
      <div class="b_dele">
        <%= link_to 'Delete' %>
      </div>
    </div>
  </div>
  <% end %>




</div>

app/views/photos/new.html.erb
<%= render :partial => "form" %>

app/views/photos/show.html.erb
<header id="header">
  <div class="container">
    <nav>
      <div class="album_name">
        <h2>
          Photo Book
        </h2>
        <div class="createbutton">
          <%= link_to "Back to index", photos_path %>
        </div>
      </div>
    </nav>
  </div>
</header>
<br>
<hr>
<br>

<div class="container">
  <div class="show_head">
    <div class="show_title">
      <%= @photo.title %>
      <%= link_to 'Edit', edit_photo_path %>
      <%= link_to 'Delete', photo_path, method: :delete, data:{confirm: "Are you sure?"} %>
    </div>
    <div class="show_date">
      <%= @photo.date %>
    </div>
  </div>

  <div class="show_pic">
    <%= image_tag @photo.file_location.url, style: 'max-height: 500px; max-width: 500px', class: "imgage-thumbnail" %>
  </div>

  <div class="show_detail">
    <%= simple_format(@photo.description) %>
  </div>

  <div class="btn_page_article">
    <div class="p_page">
      <%= link_to "< prev" %>
      <%= link_to "next >" %>
    </div>
    <div class="p_article">
      <%= link_to "< prev article" %>
      <%= link_to "next article >" %>
    </div>

  </div>
  
</div>